kind: pipeline
name: default

steps:
- name: install
  image: composer
  commands:
  - composer install

- name: test
  image: php:7.2
  commands:
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/
